### ISSUE TITLE
[CODAP] Chemistry lesson using Gas Properties + CODAP

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/gas-properties#291]
@kathy-phet mentioned that for the upcoming 2025 ChemEd Conference, we'd like to showcase our work on the Gas Properties CODAP wrappers by creating/publishing a CODAP environment and accompanying lesson targeted at an introductory chemistry topic (most likely ideal gas law). @Nancy-Salpepi is going to review the existing wrapper at https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://phet-dev.colorado.edu/html/gas-properties/1.2.0-dev.3/phet-io/wrappers/codap/data-activity.html and provide recommendations for updates to suit a HS chemistry lesson on the ideal gas law. Thanks @Nancy-Salpepi!

**Comment by matthew-blackman** [comment]
All of the changes have been implemented and should be working in the link below. Let me know if there's anything I missed!

https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://phet-dev.colorado.edu/html/gas-properties/1.2.0-dev.4/phet-io/wrappers/codap/data-activity.html

**Comment by Nancy-Salpepi** [comment]
@matthew-blackman I see that even if students select Celsius and KPa, the units are automatically converted in CODAP. Wondering if this was a specific request by someone?

Students should know how to convert from one unit to another. They should also be able to discover why we don't use Celsius in calculations.

**Comment by matthew-blackman** [comment]
Discussed this with @Nancy-Salpepi and we landed on the following design improvements:

- Checkbox sections for the Container, Particles, Pressure, Temperature and Tools
- Two different attributes for pressure (atm and kPa)
- Two different attributes for temperature (K and °C)

All changes are implemented in the prior commit. Let me know if there's more feedback to address @Nancy-Salpepi!

**Comment by Nancy-Salpepi** [comment]
Quick question @matthew-blackman  --
In the attached screenshot I was expecting a dash to appear under the Celsius column. Does the value still appear because of how the sim is designed in studio?

**Comment by Nancy-Salpepi** [comment]
I needed another opinion so I asked @KatieWoe. She pointed out that instructors might want both temperature units collected at once, even though the sim can only display 1 at a time. I thought that was a great reason for keeping things as they are!

Also, when meeting with her, we discovered a problem with the Wall Collisions (+ sample period data). If I have them both checked, but don't hit that play button, it will just repeat the last values that were recorded in CODAP. That leads to misleading data. I'm not sure how to get around that, but I hope you do! 

In this example I increased the temperature, but forgot to press the play button in the Wall Collisions dialog. 

<img width="561" alt="Image" src="https://github.com/user-attachments/assets/3f691840-39af-4a72-821c-1176bdcf55e1" />

**Comment by Nancy-Salpepi** [comment]
Everything else seems to be working well!

**Comment by matthew-blackman** [comment]
> Also, when meeting with her, we discovered a problem with the Wall Collisions (+ sample period data). If I have them both checked, but don't hit that play button, it will just repeat the last values that were recorded in CODAP. That leads to misleading data. I'm not sure how to get around that, but I hope you do!

Thanks for flagging this — I appreciate you walking through the behavior with @KatieWoe. I want to clarify a bit how the data collection system is designed to work here.

The data transfer is intentionally simple: whatever tool values are currently displayed at the moment the user clicks “Record data” get sent to CODAP. That includes the Wall Collisions reading — it doesn’t auto-update in the background or check for whether it has been reset. This mirrors the way students would collect data in a real lab: if they forget to start the stopwatch or misread a dial, they’ll collect flawed data, and that’s part of the scientific process.

In the case that the student checked the box for Wall Collisions but didn’t press play before recording, the reading wouldn't update —just like forgetting to run the experiment before taking a measurement. We’ve deliberately left room for user error to preserve the investigative nature of the sim.

That said, I’d be open to hearing if she had a specific alternative in mind for how this could behave differently while still keeping things clear and consistent for students.

**Comment by Nancy-Salpepi** [comment]
Thanks for taking the time to explain this @matthew-blackman. I will update my activity to account for this behavior.

**Comment by Nancy-Salpepi** [comment]
@LindaStegemann wondering if you had a bit of time to take [dev version ](https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://phet-dev.colorado.edu/html/gas-properties/1.2.0-dev.5/phet-io/wrappers/codap/data-activity.html) for a spin? 

Here is the accompanying [activity](https://docs.google.com/document/d/1tOYSulSPacuPKMuABSBD4wrRGcjxJ4Su5P4YaEs-eG0/edit?usp=sharing). Feel free to add comments to the doc. 

Would love your opinion, if you have the time.

**Comment by matthew-blackman** [comment]
@kathy-phet this issue is ready for next steps. Please advise how the CODAP wrapper should be published so that we can share it with conference attendees.

**Comment by Nancy-Salpepi** [comment]
@matthew-blackman, FYI--Linda thought the wrapper was good to go. From slack:

>Nancy Salpepi
Morning. Just a reminder that MB’s last full day is tomorrow. Do you think you will have any time to look at CODAP today? Since you are writing the presentation, you might want to make changes to how I asked for it to be set up, especially if you decide to go with a different lesson than the one I created.

>Linda Stegemann
I don't see anything else I'd want in the set up. You could use it as is for each of the gas laws, ideal gas law, and KMT.

>Linda Stegemann
My idea:
Why do we often see ruptured tires along the road during the summer and not during the winter? Develop a method to find a cause, then collect and organize data to justify your conclusion. Then, explain this phenomena based on your scientific evidence, being sure to include "volume," "pressure," "temperature," and "amount of particles" in your answer.

>Nancy Salpepi
Thanks for taking a look. Feel free to create an activity around your idea instead of what I did.
